license = "BSD3"
with_readme = true

[files]
directories = ["src", "hs"]
templates = [ "src/{{ project }}.dats"
            , "hs/{{ project }}.cabal"
            , "hs/{{ Project }}.hs"
            , ".travis.yml"
            , ".stylish-haskell.yaml"
            , ".hlint.yaml"
            , ".yamllint"
            , ".gitignore"
            , ".ctags"
            , ".atsfmt.toml"
            , "atspkg.dhall"
            ]

[config]
version = "0.1.0.0"
version_control = "git"
